// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TranslationProjectManagement.Data;

#nullable disable

namespace TranslationProjectManagement.Migrations
{
    [DbContext(typeof(TranslationDbContext))]
    partial class TranslationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TranslationProjectManagement.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Description for Project Alpha",
                            EndDate = new DateTime(2024, 10, 28, 19, 16, 43, 273, DateTimeKind.Local).AddTicks(2557),
                            Name = "Project Alpha",
                            StartDate = new DateTime(2024, 7, 28, 19, 16, 43, 273, DateTimeKind.Local).AddTicks(2495),
                            Status = "In Progress"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Description for Project Beta",
                            EndDate = new DateTime(2025, 2, 28, 19, 16, 43, 273, DateTimeKind.Local).AddTicks(2562),
                            Name = "Project Beta",
                            StartDate = new DateTime(2024, 8, 28, 19, 16, 43, 273, DateTimeKind.Local).AddTicks(2561),
                            Status = "Not Started"
                        });
                });

            modelBuilder.Entity("TranslationProjectManagement.Models.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("GeneratedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("ReportData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Reports");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GeneratedOn = new DateTime(2024, 8, 23, 19, 16, 43, 273, DateTimeKind.Local).AddTicks(2603),
                            ProjectId = 1,
                            ReportData = "Report data for Project Alpha"
                        },
                        new
                        {
                            Id = 2,
                            GeneratedOn = new DateTime(2024, 8, 28, 19, 16, 43, 273, DateTimeKind.Local).AddTicks(2605),
                            ProjectId = 2,
                            ReportData = "Report data for Project Beta"
                        });
                });

            modelBuilder.Entity("TranslationProjectManagement.Models.Taks", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssignedTo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssignedTo = "Alice Johnson",
                            Deadline = new DateTime(2024, 8, 18, 19, 16, 43, 273, DateTimeKind.Local).AddTicks(2580),
                            Name = "Design UI",
                            ProjectId = 1,
                            Status = "Completed"
                        },
                        new
                        {
                            Id = 2,
                            AssignedTo = "Bob Smith",
                            Deadline = new DateTime(2024, 9, 7, 19, 16, 43, 273, DateTimeKind.Local).AddTicks(2588),
                            Name = "Develop Backend",
                            ProjectId = 1,
                            Status = "In Progress"
                        },
                        new
                        {
                            Id = 3,
                            AssignedTo = "Charlie Brown",
                            Deadline = new DateTime(2024, 9, 17, 19, 16, 43, 273, DateTimeKind.Local).AddTicks(2592),
                            Name = "Gather Requirements",
                            ProjectId = 2,
                            Status = "Not Started"
                        });
                });

            modelBuilder.Entity("TranslationProjectManagement.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Role = "Project Manager",
                            UserName = "Alice Johnson"
                        },
                        new
                        {
                            Id = 2,
                            Role = "Translator",
                            UserName = "Bob Smith"
                        },
                        new
                        {
                            Id = 3,
                            Role = "Translator",
                            UserName = "Charlie Brown"
                        });
                });

            modelBuilder.Entity("TranslationProjectManagement.Models.Report", b =>
                {
                    b.HasOne("TranslationProjectManagement.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("TranslationProjectManagement.Models.Taks", b =>
                {
                    b.HasOne("TranslationProjectManagement.Models.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("TranslationProjectManagement.Models.Project", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
